apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: Namespace created to carry out experiments
    openshift.io/display-name:  Playpen project
  name: tech-beaker-01
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: welcome-php
  name: welcome-php
  namespace: tech-beaker-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome-php
  strategy: {}
  template:
    metadata:
      labels:
        app: welcome-php
    spec:
      containers:
      - image: quay.io/redhatworkshops/welcome-php:latest
        name: welcome-php
        resources: {}

---

apiVersion: v1
kind: Service
metadata:
  name: welcome-php
  namespace: tech-beaker-01
  labels:
    app: welcome-php
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: welcome-php
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: welcome-php
  namespace: tech-beaker-01
  labels:
    app: welcome-php
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: welcome-php
    weight: 100
  wildcardPolicy: None
